// kinds 30550-30554 fa:Kanban* validator (evenflow EFB-24).
//
// This file is the contract between two repos. Evenflow builds and signs these
// events; the gateway only checks them. A change on either side that isn't
// mirrored is a silent publish failure — evenflow keeps stamping
// substrate_event_id NULL and nobody notices until someone asks why a public
// board has no substrate history.
//
// The GOLDEN fixtures below were generated by running evenflow's real builders
// (src/lib/audience/audience-events.ts, buildKanban*) with fixed ids and a
// fixed createdAt — not hand-written here. Regenerate them in the same PR as
// any builder change.
//
// KNOW WHAT THIS GUARD DOES AND DOES NOT CATCH. It catches READER-side drift
// only: a change to blake3ContentTag, or to validation, breaks the fixtures and
// this suite goes red. It does NOT catch WRITER-side drift. A change to
// evenflow's BUILDER — adding a content field, renaming a tag — leaves each
// fixture in sync with its own hash and therefore still green, while both drift
// out of sync with what evenflow actually publishes. Self-consistent means
// self-decoupled from the world: the suite goes on passing against a shape
// production stopped emitting.
//
// EFB-32 is the worked example. evenflow added a `deleted` field to
// buildKanbanBoard's content; the board golden's blake3 went stale; every test
// here kept passing. So the regenerate-from-the-live-builder step in the
// corresponding evenflow PR is not optional — it is the only thing that makes
// this file honest, and no test here will remind you.
//
// Signature and canonical id are NOT this validator's job (requireSignedEvent
// handles those upstream), so nothing here signs anything.

import { describe, expect, it } from "vitest";
import { blake3ContentTag } from "../lib/blake3-tag";
import {
  KIND_KANBAN_BOARD,
  KIND_KANBAN_COMMENT,
  KIND_KANBAN_ISSUE,
  KIND_KANBAN_SPRINT,
  KIND_KANBAN_STATUS_CHANGE,
  validateKanbanPlaintextEvent,
  type KanbanEventLike,
} from "../kanban-plaintext-validator";

const CONTEXT = "https://4a4.ai/ns/v0";
const BOARD = "97d96cac-85cb-4eec-b974-e92b59da2c78";
const ISSUE = "11111111-1111-4111-8111-111111111111";
const COMMENT = "22222222-2222-4222-8222-222222222222";
const SPRINT = "33333333-3333-4333-8333-333333333333";
const STATUS_CHANGE = "44444444-4444-4444-8444-444444444444";
const PUBKEY = "049b628c4e18d562627fd924dea8dd6fe98d4dd3094fd85a53d84c0f5219b3c2";

// ── GOLDEN: verbatim output of evenflow's buildKanban* ────────────────────

const GOLDEN: Readonly<Record<string, KanbanEventLike>> = {
  board: {
    kind: 30550,
    tags: [
      ["d", BOARD],
      ["fa:context", CONTEXT],
      ["alt", "Board Tide Test Public"],
      ["blake3", "bk-q6nlua64y3ulb7a64xnkvdxrszz5oraafxrja7krm3zvltgcg2nq"],
      ["fa:board", BOARD],
      ["fa:slug", "tide-test-public"],
    ],
    content:
      '{"@context":"https://4a4.ai/ns/v0","@type":"KanbanBoard","slug":"tide-test-public","title":"Tide Test Public","description":null,"org_id":"org-1","issue_prefix":"TTP","default_sprint_days":14,"done_window_days":14,"columns":[{"id":"c1","name":"Todo"}],"labels":[],"member_policy":"org","archived":false,"deleted":false}',
  },
  // evenflow EFB-32 gave buildKanbanBoard the `deleted` flag its issue and
  // comment siblings already had, so every 30550 now carries it — hence the
  // refreshed board blake3 above. The validator needed no change to accept
  // either of these; this fixture pair is what keeps that true.
  boardTombstone: {
    kind: 30550,
    tags: [
      ["d", BOARD],
      ["fa:context", CONTEXT],
      ["alt", "Board Tide Test Public"],
      ["blake3", "bk-tnvktq4cynehpexw4ql2u6jmy2rh5bfv7znrm3vcw3k5frn37wga"],
      ["fa:board", BOARD],
      ["fa:slug", "tide-test-public"],
      ["fa:deleted", "1"],
    ],
    content:
      '{"@context":"https://4a4.ai/ns/v0","@type":"KanbanBoard","slug":"tide-test-public","title":"Tide Test Public","description":null,"org_id":"org-1","issue_prefix":"TTP","default_sprint_days":14,"done_window_days":14,"columns":[{"id":"c1","name":"Todo"}],"labels":[],"member_policy":"org","archived":false,"deleted":true}',
  },
  issue: {
    kind: 30551,
    tags: [
      ["d", ISSUE],
      ["fa:context", CONTEXT],
      ["alt", "Issue TTP-7: Publish plaintext kinds"],
      ["blake3", "bk-a4v6j6npnshvbqhndxzybhk5wfavglokqpqh6hjkjvel3ay6kupa"],
      ["fa:board", BOARD],
      ["fa:type", "task"],
      ["fa:status", "In Progress"],
      ["fa:container", "active"],
      ["fa:sprint", SPRINT],
    ],
    content:
      '{"@context":"https://4a4.ai/ns/v0","@type":"KanbanIssue","short_id":"TTP-7","title":"Publish plaintext kinds","body":"body text","body_format":"markdown","type":"task","status":"In Progress","column_id":"c2","container":"active","assignee_pubkey":null,"priority":2,"estimate":3,"labels":["substrate"],"position":1000,"sprint_id":"33333333-3333-4333-8333-333333333333","external_state":null,"deleted":false}',
  },
  comment: {
    kind: 30552,
    tags: [
      ["d", COMMENT],
      ["fa:context", CONTEXT],
      ["alt", `Comment on issue ${ISSUE}`],
      ["blake3", "bk-pvxfkncyfxe56u7chcls274xe664lftoejch52yxfe73ua5nuira"],
      ["fa:board", BOARD],
      ["fa:issue", ISSUE],
    ],
    content: `{"@context":"https://4a4.ai/ns/v0","@type":"KanbanComment","issue_id":"${ISSUE}","author_pubkey":"${PUBKEY}","body":"a comment","body_format":"markdown","in_reply_to":null,"deleted":false}`,
  },
  statusChange: {
    kind: 30553,
    tags: [
      ["d", STATUS_CHANGE],
      ["fa:context", CONTEXT],
      ["alt", `Issue ${ISSUE}: Todo → In Progress`],
      ["blake3", "bk-67mdrlivkhocglbcrql7huweec4ih6zdqd5oybm2o4bkouclnjwa"],
      ["fa:board", BOARD],
      ["fa:issue", ISSUE],
    ],
    content: `{"@context":"https://4a4.ai/ns/v0","@type":"KanbanStatusChange","issue_id":"${ISSUE}","actor_pubkey":"${PUBKEY}","from_status":"Todo","to_status":"In Progress","from_container":"backlog","to_container":"active","occurred_at_ms":1760000000000}`,
  },
  sprint: {
    kind: 30554,
    tags: [
      ["d", SPRINT],
      ["fa:context", CONTEXT],
      ["alt", "Sprint Sprint A (active)"],
      ["blake3", "bk-ypbnybarkomqozmcprmcu5iohbrd67k7dqmzew64fw2uj7yelq4q"],
      ["fa:board", BOARD],
      ["fa:sprint", SPRINT],
      ["fa:status", "active"],
    ],
    content:
      '{"@context":"https://4a4.ai/ns/v0","@type":"KanbanSprint","name":"Sprint A","goal":"ship EFB-24","status":"active","planned_days":7,"started_at_ms":1760000000000,"completed_at_ms":null,"points_committed_start":21,"points_completed":null,"points_carried":null,"adds_mid_sprint":0}',
  },
};

/** Rebuild an event with one tag replaced or removed (undefined = remove). */
const withTag = (base: KanbanEventLike, name: string, value?: string): KanbanEventLike => {
  const tags = base.tags.filter((t) => t[0] !== name);
  if (value !== undefined) tags.push([name, value]);
  return { ...base, tags };
};

/** Replace content and re-hash, so only the field under test is wrong. */
const withContent = (base: KanbanEventLike, over: Record<string, unknown>): KanbanEventLike => {
  const content = JSON.stringify({ ...JSON.parse(base.content), ...over });
  return withTag({ ...base, content }, "blake3", blake3ContentTag(content));
};

describe("golden events from evenflow's builders", () => {
  // The drift guard. These blake3 tags were produced by evenflow, not by this
  // file — if they still match what blake3ContentTag computes here, the two
  // repos agree on content serialization byte-for-byte.
  it.each(Object.entries(GOLDEN))("%s: blake3 tag matches its content", (_name, ev) => {
    const tag = ev.tags.find((t) => t[0] === "blake3")?.[1];
    expect(tag).toBe(blake3ContentTag(ev.content));
  });

  it.each(Object.entries(GOLDEN))("%s: validates", (_name, ev) => {
    const res = validateKanbanPlaintextEvent(ev);
    expect(res.ok).toBe(true);
  });

  it("reports the parsed identity for each kind", () => {
    const board = validateKanbanPlaintextEvent(GOLDEN["board"]!);
    expect(board.ok && board.value).toMatchObject({
      kind: KIND_KANBAN_BOARD,
      type: "KanbanBoard",
      boardId: BOARD,
      dTag: BOARD,
      deleted: false,
    });

    // Same address as the live board above — that is the whole point of a
    // tombstone on a replaceable kind. A retirement published anywhere else
    // leaves the live 30550 standing and a replaying consumer resurrects the
    // board (evenflow EFB-32).
    const tombstone = validateKanbanPlaintextEvent(GOLDEN["boardTombstone"]!);
    expect(tombstone.ok && tombstone.value).toMatchObject({
      kind: KIND_KANBAN_BOARD,
      type: "KanbanBoard",
      boardId: BOARD,
      dTag: BOARD,
      deleted: true,
    });

    const issue = validateKanbanPlaintextEvent(GOLDEN["issue"]!);
    expect(issue.ok && issue.value).toMatchObject({
      kind: KIND_KANBAN_ISSUE,
      dTag: ISSUE,
      sprintId: SPRINT,
    });

    const comment = validateKanbanPlaintextEvent(GOLDEN["comment"]!);
    expect(comment.ok && comment.value).toMatchObject({
      kind: KIND_KANBAN_COMMENT,
      dTag: COMMENT,
      issueId: ISSUE,
    });

    const sc = validateKanbanPlaintextEvent(GOLDEN["statusChange"]!);
    expect(sc.ok && sc.value).toMatchObject({
      kind: KIND_KANBAN_STATUS_CHANGE,
      dTag: STATUS_CHANGE,
      issueId: ISSUE,
    });

    const sprint = validateKanbanPlaintextEvent(GOLDEN["sprint"]!);
    expect(sprint.ok && sprint.value).toMatchObject({
      kind: KIND_KANBAN_SPRINT,
      dTag: SPRINT,
      sprintId: SPRINT,
    });
  });
});

describe("kind allowlist", () => {
  it("rejects a kind outside 30550-30554", () => {
    const res = validateKanbanPlaintextEvent({ ...GOLDEN["issue"]!, kind: 30560 });
    expect(res).toMatchObject({ ok: false });
    expect(res.ok === false && res.error).toContain("30550-30554");
  });

  // The encrypted variants never come through here: private boards gift-wrap
  // and publish via /v0/audience/raw/publish-wraps.
  it("rejects an encrypted kanban kind", () => {
    const res = validateKanbanPlaintextEvent({ ...GOLDEN["issue"]!, kind: 30556 });
    expect(res).toMatchObject({ ok: false });
  });
});

describe("shared envelope", () => {
  it.each(["fa:context", "fa:board", "d", "alt", "blake3"])("requires %s", (tag) => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["issue"]!, tag, undefined));
    expect(res).toMatchObject({ ok: false });
  });

  it("rejects a wrong fa:context", () => {
    const res = validateKanbanPlaintextEvent(
      withTag(GOLDEN["issue"]!, "fa:context", "https://example.com/ns/v1"),
    );
    expect(res.ok === false && res.error).toContain("fa:context");
  });

  it("rejects an empty fa:board", () => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["issue"]!, "fa:board", ""));
    expect(res.ok === false && res.error).toContain("fa:board");
  });

  // Catches a re-serialized or tampered body without re-reading every field.
  it("rejects a blake3 that does not match content", () => {
    const res = validateKanbanPlaintextEvent(
      withTag(GOLDEN["issue"]!, "blake3", "bk-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
    );
    expect(res.ok === false && res.error).toContain("blake3");
  });

  it("rejects non-JSON content", () => {
    const bad = { ...GOLDEN["issue"]!, content: "not json" };
    const res = validateKanbanPlaintextEvent(withTag(bad, "blake3", blake3ContentTag("not json")));
    expect(res.ok === false && res.error).toContain("valid JSON");
  });

  it("rejects a JSON array as content", () => {
    const arr = "[1,2,3]";
    const res = validateKanbanPlaintextEvent(
      withTag({ ...GOLDEN["issue"]!, content: arr }, "blake3", blake3ContentTag(arr)),
    );
    expect(res.ok === false && res.error).toContain("JSON object");
  });

  it("rejects a wrong content @context", () => {
    const res = validateKanbanPlaintextEvent(
      withContent(GOLDEN["issue"]!, { "@context": "https://example.com" }),
    );
    expect(res.ok === false && res.error).toContain("@context");
  });
});

describe("per-kind shape", () => {
  it("rejects a content @type that does not match the kind", () => {
    const res = validateKanbanPlaintextEvent(
      withContent(GOLDEN["issue"]!, { "@type": "KanbanBoard" }),
    );
    expect(res.ok === false && res.error).toContain("KanbanIssue");
  });

  it.each(["fa:type", "fa:status", "fa:container"])("issue requires %s", (tag) => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["issue"]!, tag, undefined));
    expect(res).toMatchObject({ ok: false });
  });

  it("comment requires fa:issue", () => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["comment"]!, "fa:issue", undefined));
    expect(res).toMatchObject({ ok: false });
  });

  it("board requires fa:slug", () => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["board"]!, "fa:slug", undefined));
    expect(res).toMatchObject({ ok: false });
  });

  it.each(["fa:sprint", "fa:status"])("sprint requires %s", (tag) => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["sprint"]!, tag, undefined));
    expect(res).toMatchObject({ ok: false });
  });

  // These kinds are parameterized-replaceable, so `d` decides what a republish
  // REPLACES. A board event keyed on anything but its board id would overwrite
  // an unrelated address.
  it("board d tag must equal fa:board", () => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["board"]!, "d", "some-other-id"));
    expect(res.ok === false && res.error).toContain("fa:board");
  });

  it("sprint d tag must equal fa:sprint", () => {
    const res = validateKanbanPlaintextEvent(withTag(GOLDEN["sprint"]!, "d", "some-other-id"));
    expect(res.ok === false && res.error).toContain("fa:sprint");
  });

  // An issue's d tag is its own id, which appears in no other tag — so it is
  // only required to be present and non-empty.
  it("accepts an issue whose d tag is its own id", () => {
    const res = validateKanbanPlaintextEvent(GOLDEN["issue"]!);
    expect(res.ok && res.value.dTag).toBe(ISSUE);
  });
});

describe("tombstones", () => {
  // evenflow publishes deletions as deleted:true at the entity's OWN address
  // rather than via NIP-09 — a tombstone anywhere else would leave the last
  // live version standing for a replaying consumer.
  it("accepts deleted:true and surfaces it", () => {
    const res = validateKanbanPlaintextEvent(withContent(GOLDEN["issue"]!, { deleted: true }));
    expect(res.ok && res.value.deleted).toBe(true);
  });

  it("rejects a non-boolean deleted", () => {
    const res = validateKanbanPlaintextEvent(withContent(GOLDEN["issue"]!, { deleted: "yes" }));
    expect(res.ok === false && res.error).toContain("deleted");
  });
});
